version: '3.8'

networks:
    backend:
services:
    nginx:
        image: nginx:stable-alpine
        container_name: hkh-nginx
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - backend
    mysql:
        image: mysql:8.0
        container_name: hkh-mysql
        restart: unless-stopped
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - backend
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: hkh-php
        volumes:
            - ./src/:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - backend
    composer:
        image: composer:2.4
        container_name: hkh-composerr
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        networks:
            - backend
    npm:
        image: node:18.12.1
        container_name: hkh-npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: [ 'npm' ]
    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: hkh-artisan
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
        working_dir: /var/www/html
        entrypoint: [ 'php', '/var/www/html/artisan' ]
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: hkh-phpmyadmin
        environment:
              PMA_PMADB: 1
              PMA_ARBITRARY: 1
              MYSQL_ROOT_PASSWORD: secret
        restart: always
        depends_on:
             - mysql
        ports:
            - "8080:80"
        #volumes:
            # - ./mysql:/etc/phpmyadmin/config.user.inc.php
        networks:
            - backend
        links:
            - mysql